# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 09:09
from __future__ import unicode_literals

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170706_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='coverimg',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.upload_location),
        ),
    ]
