# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_coverimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='text',
            new_name='content',
        ),
    ]
