# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20170710_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
